spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

  data:
    redis:
      host: trello-redis-ro.vx8ixf.ng.0001.apn2.cache.amazonaws.com
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.url}/${database.name}
    username: ${mysql.username}
    password: ${mysql.password}
server:
  port: 8080
